#!/bin/bash

echo "asciidoctor -r asciidoctor-diagram source/designPattern.adoc -o designPattern.html -a stylesheet=stylesheet.css"
asciidoctor -r asciidoctor-diagram source/designPattern.adoc -o designPattern.html -a stylesheet=stylesheet.css


echo "asciidoctor -r asciidoctor-diagram source/index.adoc -o index.html -a stylesheet=stylesheet.css"
asciidoctor -r asciidoctor-diagram source/index.adoc -o index.html -a stylesheet=stylesheet.css

echo "asciidoctor -r asciidoctor-diagram source/asciidoc.adoc -o asciidoc.html -a stylesheet=stylesheet.css"
asciidoctor -r asciidoctor-diagram source/asciidoc.adoc -o asciidoc.html -a stylesheet=stylesheet.css

