@startuml
skinparam participant {
    BorderColor Black
    BorderThickness 1
    FontName Helvetica
    FontSize 13
    BackgroundColor 0066A1
    HeaderBackgroundColor 0066A1
    AttributeFontColor black
    FontColor White
    FontStyle bold
}


skinparam sequence {
    ArrowColor Black
    GroupBackgroundColor 0066A1
    GroupHeaderFontColor White
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    FontColor red
}

skinparam class  {
    ArrowColor Black
    BackgroundColor transparent
    GroupHeaderFontColor White
    BorderColor  Black
    LifeLineBackgroundColor White
    FontColor Black
}

skinparam note {
    BackgroundColor  transparent
    FontColor 3284B3
    BorderColor black
}


class Petfactory{
{method} + getPet(): Pet
}
class Pet{
{method} + sound()
}
class Cat{
{method} + sound()
}
class Client {
{method}+ main (String[])
}
class Dog{
{method} + sound()
}

Client ..> Pet
Client  ..> Petfactory
Pet <|-- Dog
Pet <|-- Cat
Petfactory ..> Dog
Petfactory ..> Cat

@enduml