//
// file: index.adoc
//
= Design Pattern
:sectnums:
:toc: left
:toclevels: 3

:toc!:

*2020-10-20*

Design Pattern in oriented object development allow programmers using technics to obtain lighter sources and easier to enrich.
The purpose of this chapter is to present  most famous design patterns known. All those  chapters are illustrated with examples with a github project available https://github.com/florianley/designPaterns[here]

== Creation Models
=== Factory
The factory allow to creat a different object type according to the context. Thanks to polymorphism an object is still the same than the mother class but executed methods come from the created instance.

Factory method is useful when :

* The client can't define an object type before the execution
* There is a desire to centralize the creation of objects

==== Factory with an abstract way

[[main-classes]]
.The PlantUML block extension class
[plantuml, sample-plantuml-diagram, alt="Class diagram", width=135, height=118]
----
@startuml

skinparam participant {
    BorderColor Black
    BorderThickness 1
    FontName Helvetica
    FontSize 13
    BackgroundColor 0066A1
    HeaderBackgroundColor 0066A1
    AttributeFontColor black
    FontColor White
    FontStyle bold

}


skinparam sequence {
    ArrowColor Black
    GroupBackgroundColor 0066A1
    GroupHeaderFontColor White
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    FontColor red
}

skinparam note {
    BackgroundColor  transparent
    FontColor 3284B3
    BorderColor black
}


Kevin -> Alice : test

@enduml
----

plantuml::Factory.puml[format=svg, alt="Class diagram", width=300, height=200]


[plantuml, diagram-classes, png]
....
@startuml

class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
@enduml
....
