//
// file: designPattern.adoc
//
= Design Pattern
:sectnums:
:toc: left
:toclevels: 3
:imagesdir: img
:source-highlighter: coderay
:coderay-css: style

*2020-10-20*

Design Pattern in oriented object software development allows programmers to use techniques in order to obtain lighter sources and easiest to enrich.The purpose of this chapter is to present  most famous design patterns known. All those  chapters are illustrated with examples through my github project available https://github.com/florianley/designPaterns[here]

== Creation Models
=== Factory
The factory allow to create a different object type according to the context. Thanks to polymorphism an object is still the same than the mother class but executed methods come from the created instance.

Factory method is useful when :

* The client can't define an object type before the execution
* There is a desire to centralize the creation of objects

==== Factory by legacy
The main factory is abstract. A Factory has to be indirectly linked to an abstract object. The link is made through Factories legacies and object's legacies. In the following case, every Wolkswagenfactories (WolksVagenGolfFactory and WolksVagenPassatFactory)  instenciate the same method from Wolkswagenfactories but it produce a car of their own type

plantuml::plantuml/designPattern/Factory.puml[format=svg, alt="Class diagram",align=center]

With this organization, the client implementation could be achieved by the following way :

[source,java]
----
public class Client {
    public static void main (String[] args){
        WolksVagenCar myCar ;

        System.out.println("use of first Factory");
        myCar = new Golf();
        myCar.methodeA();

        System.out.println("use of second Factory");
        myCar = new Passat();
        myCar.methodeA();
    }
}
----

With the following result :

[source,bash]
use of first Factory
I'm a Golf
use of second Factory
I'm a Passat

==== Factory with parameter way
The factory contains a method in charge of building an object based on the parameter asked. In the following example, the petFactory contains getPet'method in charge to create a cat or a dog depending on the parameter sent.

plantuml::plantuml/designPattern/Factory2.puml[format=svg, alt="Class diagram",align=center]

In this case, Client class have to look like this :

[source,java]
----
public class Client {
    public static void main (String[] args){
        PetFactory petFactory = new PetFactory();

        Pet pet;

        System.out.println("first pet creation :");
        pet = petFactory.getPet(PetFactory.DOG);
        pet.sound();

        System.out.println("second pet creation :");
        pet = petFactory.getPet(PetFactory.CAT);
        pet.sound();

    }
}
----

With the following result :
[source,bash]
first pet creation :
the dog barks
second pet creation :
the cat meows

=== Abstract Factory

plantuml::plantuml/designPattern/AbstractFactory.puml[format=svg, alt="Class diagram",align=center]

